/* Punto 02 */
SELECT * FROM TOP_SPOTIFY;


/* Punto 03 */
SELECT * FROM TOP_SPOTIFY AS TS
ORDER BY TS.GENERO ASC;


/* Punto 04 */
SELECT * FROM TOP_SPOTIFY AS TS
ORDER BY TS.GENERO ASC, TS.ARTISTA ASC;


/* Punto 05 */
SELECT TS.ARTISTA, TS.TITULO, TS.GENERO FROM TOP_SPOTIFY AS TS
ORDER BY TS.ARTISTA ASC, TS.TITULO ASC
LIMIT 10;


/* Punto 06 */
SELECT TS.ARTISTA, TS.TITULO, TS.GENERO FROM TOP_SPOTIFY AS TS
ORDER BY TS.ARTISTA ASC, TS.TITULO ASC
LIMIT 5 OFFSET 10;


/* Punto 07 */
SELECT * FROM TOP_SPOTIFY AS TS
WHERE ARTISTA = 'Lady Gaga';


/* Punto 08 */
SELECT * FROM TOP_SPOTIFY AS TS
WHERE GENERO = 'POP'
ORDER BY TS.TITULO ASC;


/* Punto 09 */
SELECT * FROM TOP_SPOTIFY AS TS
WHERE TS.GENERO = 'POP' AND TS.ANO = 2015
ORDER BY TS.ARTISTA ASC, TS.TITULO ASC;


/* Punto 10 */
SELECT * FROM TOP_SPOTIFY AS TS
WHERE TS.ANO < 2011 AND TS.GENERO = 'Dance Pop'
ORDER BY TS.TITULO ASC;