/* Punto 01 */
CREATE DATABASE TRANSPORTISTA;


/* Punto 02 */
USE TRANSPORTISTA;

CREATE TABLE CAMIONEROS (
    ID_CAMIONEROS int NOT NULL AUTO_INCREMENT,
    NOMBRE varchar(255) NOT NULL,
    DIRECCION varchar(255) NOT NULL,
    TELEFONO int NOT NULL,
    SUELDO int NOT NULL,
    PRIMARY KEY (ID_CAMIONEROS)
);

CREATE TABLE CAMIONES (
    MATRICULA int NOT NULL,
    MARCA varchar(255) NOT NULL,
    MODELO varchar(255) NOT NULL,
    POTENCIA varchar(255) NOT NULL,
    TIPO varchar(255) NOT NULL,
    PRIMARY KEY (MATRICULA)
);

CREATE TABLE DETALLE_DE_PAQUETES (
    ID_DETALLE_DE_PAQUETES int NOT NULL AUTO_INCREMENT,
    ID_CAMIONEROS int NOT NULL,
    MATRICULA int NOT NULL,
    PRIMARY KEY (ID_DETALLE_DE_PAQUETES),
    CONSTRAINT FK_CAMIONERO_DETALLE FOREIGN KEY (ID_CAMIONEROS) REFERENCES CAMIONEROS(ID_CAMIONEROS),
    CONSTRAINT FK_CAMION_DETALLE FOREIGN KEY (MATRICULA) REFERENCES CAMIONES(MATRICULA)
);

CREATE TABLE CIUDADES (
    ID_CIUDADES int NOT NULL AUTO_INCREMENT,
    NOMBRE varchar(255) NOT NULL,
    PRIMARY KEY (ID_CIUDADES)
);

CREATE TABLE PAQUETE (
    ID_PAQUETE int NOT NULL AUTO_INCREMENT,
    DESCRIPCIONES varchar(255) NOT NULL,
    DESTINATARIO varchar(255) NOT NULL,
    DIRECCION varchar(255) NOT NULL,
    ID_CAMIONEROS int NOT NULL,
    ID_CIUDADES int NOT NULL,
    PRIMARY KEY (ID_PAQUETE),
    CONSTRAINT FK_CAMIONERO_PAQUETE FOREIGN KEY (ID_CAMIONEROS) REFERENCES CAMIONEROS(ID_CAMIONEROS),
    CONSTRAINT FK_CIUDAD_PAQUETE FOREIGN KEY (ID_CIUDADES) REFERENCES CIUDADES(ID_CIUDADES)
);




INSERT INTO CAMIONES
VALUES (101345, 'SCANIA', 'R 340', '360CV', 'ARTICULADO');

INSERT INTO CAMIONES
VALUES (123789, 'FIAT', '619 N1', '260CV', 'CONTENEDOR');

INSERT INTO CAMIONES
VALUES (178349, 'IVECO', 'CURSOR 330', '330CV','RIGIDO');