/* Punto 01 */
CREATE DATABASE TRANSPORTISTA;


/* Punto 02 */
USE TRANSPORTISTA;

CREATE TABLE CAMIONEROS (
    ID_CAMIONEROS int NOT NULL AUTO_INCREMENT,
    NOMBRE varchar(255) NOT NULL,
    DIRECCION varchar(255) NOT NULL,
    TELEFONO varchar(255) NOT NULL,
    SUELDO int NOT NULL,
    PRIMARY KEY (ID_CAMIONEROS)
);

CREATE TABLE CAMIONES (
    MATRICULA int NOT NULL,
    MARCA varchar(255) NOT NULL,
    MODELO varchar(255) NOT NULL,
    POTENCIA varchar(255) NOT NULL,
    TIPO varchar(255) NOT NULL,
    PRIMARY KEY (MATRICULA)
);

CREATE TABLE DETALLE_DE_PAQUETES (
    ID_DETALLE_DE_PAQUETES int NOT NULL AUTO_INCREMENT,
    ID_CAMIONEROS int NOT NULL,
    MATRICULA int NOT NULL,
    PRIMARY KEY (ID_DETALLE_DE_PAQUETES),
    CONSTRAINT FK_CAMIONERO_DETALLE FOREIGN KEY (ID_CAMIONEROS) REFERENCES CAMIONEROS(ID_CAMIONEROS),
    CONSTRAINT FK_CAMION_DETALLE FOREIGN KEY (MATRICULA) REFERENCES CAMIONES(MATRICULA)
    ON UPDATE CASCADE
);

CREATE TABLE CIUDADES (
    ID_CIUDADES int NOT NULL AUTO_INCREMENT,
    NOMBRE varchar(255) NOT NULL,
    PRIMARY KEY (ID_CIUDADES)
);

CREATE TABLE PAQUETE (
    ID_PAQUETE int NOT NULL AUTO_INCREMENT,
    DESCRIPCIONES varchar(255) NOT NULL,
    DESTINATARIO varchar(255) NOT NULL,
    DIRECCION varchar(255) NOT NULL,
    ID_CAMIONEROS int NOT NULL,
    ID_CIUDADES int NOT NULL,
    PRIMARY KEY (ID_PAQUETE),
    CONSTRAINT FK_CAMIONERO_PAQUETE FOREIGN KEY (ID_CAMIONEROS) REFERENCES CAMIONEROS(ID_CAMIONEROS),
    CONSTRAINT FK_CIUDAD_PAQUETE FOREIGN KEY (ID_CIUDADES) REFERENCES CIUDADES(ID_CIUDADES)
);


/* Punto 03 */
INSERT INTO CAMIONES
VALUES (101345, 'SCANIA', 'R 340', '360CV', 'ARTICULADO');

INSERT INTO CAMIONES
VALUES (123789, 'FIAT', '619 N1', '260CV', 'CONTENEDOR');

INSERT INTO CAMIONES
VALUES (178349, 'IVECO', 'CURSOR 330', '330CV', 'RIGIDO');

INSERT INTO CAMIONEROS
VALUES (NULL, 'AUGUSTO DOMINGUEZ', 'LA HAYA 4078', '01165983412', 310000);

INSERT INTO CAMIONEROS
VALUES (NULL, 'RAUL MARTINEZ', 'THAMES 582', '03871234555', 275000);

INSERT INTO CAMIONEROS
VALUES (NULL, 'IVAN ROBLEDO', 'CARLOS TELLIER 899', '02211257895', 365000);

INSERT INTO CIUDADES
VALUES (NULL, 'MENDOZA');

INSERT INTO CIUDADES
VALUES (NULL, 'MISIONES');

INSERT INTO CIUDADES
VALUES (NULL, 'SALTA');


/* Punto 04 */
INSERT INTO PAQUETE
VALUES (NULL, 'VIDRIO TEMPLADO Y PROTECTOR PARA CELULAR', 'BRIAN CESPEDES', 'JULIAN ALVAREZ 321', 1, 2);

INSERT INTO PAQUETE
VALUES (NULL, 'CELULAR', 'MIRANDA MARENZI', 'HUMBOLDT 555', 3, 2);

INSERT INTO DETALLE_DE_PAQUETES
VALUES (NULL, 1, 101345);

INSERT INTO DETALLE_DE_PAQUETES
VALUES (NULL, 3, 123789);


/* Punto 05 */
INSERT INTO PAQUETE
VALUES (NULL, 'PARLANTE PORTATIL', 'VALENTINA LANZILLOTA', 'MURILLO 356', 2, 1);

INSERT INTO PAQUETE
VALUES (NULL, 'LICUADORA', 'LEANDRO AVALOS', 'COSTA RICA 888', 1, 1);

INSERT INTO DETALLE_DE_PAQUETES
VALUES (NULL, 2, 178349);

INSERT INTO DETALLE_DE_PAQUETES
VALUES (NULL, 1, 178349);


/* Punto 06 */
UPDATE CAMIONES
SET MATRICULA = 8795
WHERE MARCA = 'SCANIA';


/* Punto 07 */
SELECT SUM(SUELDO) AS MONTO_TOTAL_DE_SUELDOS
FROM CAMIONEROS;